### ISSUE TITLE
We should replace the term "core team" in the process doc

### ISSUE THREAD

**Issue by mikecroft** [microprofile/evolution#29]
As [John mentioned](https://github.com/eclipse/microprofile-evolution-process/pull/28#issuecomment-303077639), "core team" should be changed.

One option would be to use Eclipse approved committers:
https://projects.eclipse.org/projects/technology.microprofile/who

**Comment by OndroMih** [comment]
+1 for project committers

However, we should also count those who have been accepted as committers but have not completed the Eclipse paperwork or have any problems to join the committers' list. In that case, we would need to maitain a separate list of such people n top of the committer list.

**Comment by OndroMih** [comment]
In fact, it should be enough to define the term "Core team" in a prominent place and leave it in the document as is, without replacing it everywhere.

**Comment by Emily-Jiang** [comment]
I'm fine with MicroProfile Core team. I think Core team should be similar to PMC.

**Comment by kenfinnigan** [comment]
closing as out of date with new process
