### ISSUE TITLE
Reservation file for MP proposal numbers?

### ISSUE THREAD

**Issue by kwsutter** [microprofile/evolution#32]
I ran into an issue when I created the proposal for MicroProfile 1.1.  I just looked at the "proposals" subdirectory and saw the next logical number was 0005.  But, because of other in-flight proposals, this number was already in use by the JWT proposal.  So, how can someone know what the proper proposal number should be?

My suggestion is to just create a top-level file that can easily be updated with the MP proposal number along with the title of the proposal.  As new proposals arise, we could update that file so that everyone can see at a glance all of the proposal numbers and associated titles.

I'm open to other ideas.  I'm just looking for something simple so that future proposals don't hit the same problem that I did.  Thanks.

**Comment by kenfinnigan** [comment]
closing as out of date with proposal changes
