### ISSUE TITLE
Create proposal for OpenAPI v3 

### ISSUE THREAD

**Issue by arthurdm** [microprofile/evolution#36]
Create proposal for OpenAPI v3 Java specification.

**Comment by arthurdm** [comment]
Will open appropriate issue on my fork (instead of the origin) =)

**Comment by mikecroft** [comment]
@kenfinnigan - since the process is changing/has changed, will this be necessary for OpenAPI? Should we use the sandbox repository for fully-formed proposals like an existing spec, or is this repo still relevant?

**Comment by kenfinnigan** [comment]
I don't think the repo will be relevant any longer.

Hope to have some time to work on it today

**Comment by arthurdm** [comment]
Thanks for the feedback guys.  Should I not be making a proposal here then?  I started one in my fork at https://github.com/arthurdm/microprofile-evolution-process/blob/master/proposals/0009-OpenAPI.md

fyi, @kwsutter

**Comment by kenfinnigan** [comment]
I wouldn't do anything here right now
