### ISSUE TITLE
come up with canonical URL paths we use for swagger, liveness checks, readiness checks etc

### ISSUE THREAD

**Issue by jstrachan** [microprofile/evolution#5]
It'd be nice to come up with some conventions for microprofile apps that make them easy to automatically tool when its ran on a container platform like kubernetes.

For example if we had canonical paths for exposing the swagger metadata, we could annotate the `Deployment` automatically via the [fabric8 maven plugin](https://github.com/fabric8io/fabric8-maven-plugin/) (see this issue https://github.com/fabric8io/fabric8-maven-plugin/issues/645). 

Similarly it'd be nice to have a canonical URL path for liveness and readiness checks
http://kubernetes.io/docs/user-guide/liveness/
so that we can automatically add good liveness & readiness probes when deploying a microprofile app on kubernetes https://github.com/fabric8io/fabric8-maven-plugin/issues/645

**Comment by heiko-braun** [comment]
@jstrachan please put your thoughts into a proposal using the prepared template and submit a PR for this. It needs to be a document under `evolution/proposals` i.e. `evolution/proposals/xxxx-common-apidoc-endpoint.adoc` that outlines the motivation and ideas.  We'll use this as baseline to discuss your proposal then.

**Comment by heiko-braun** [comment]
The template can be found here: https://github.com/microprofile/evolution/blob/master/0000-template.md

**Comment by johnament** [comment]
This is resolved by #12 and #14 so we can probably close once one of those are in.

**Comment by kenfinnigan** [comment]
Closing as already included
